# Generated by Django 6.0.4 on 2026-04-14 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=30)),
                ('counteroffer_count', models.IntegerField(default=0)),
                ('max_counteroffers', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('offered', 'Offered'), ('requested', 'Requested')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swap_mode', models.CharField(blank=True, choices=[('in_person', 'In-Person Meetup'), ('mail', 'Mail Swap')], max_length=20, null=True)),
                ('mode_decided_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_location', models.TextField(blank=True, null=True)),
                ('proposed_datetime', models.DateTimeField(blank=True, null=True)),
                ('in_person_confirmed_initiator', models.BooleanField(default=False)),
                ('in_person_confirmed_target', models.BooleanField(default=False)),
                ('in_person_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_from_address', models.TextField(blank=True, null=True)),
                ('shipping_to_address', models.TextField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, choices=[('USPS', 'USPS'), ('UPS', 'UPS'), ('FedEx', 'FedEx'), ('DHL', 'DHL')], max_length=50, null=True)),
                ('outbound_tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('swap_completed_at', models.DateTimeField(blank=True, null=True)),
                ('addresses_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
