# Generated by Django 6.0.4 on 2026-04-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('swaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='initiator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='swaps.offer'),
        ),
        migrations.AddField(
            model_name='swapdetails',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_details', to='swaps.offer'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['initiator_user_id'], name='swaps_offer_initiat_466e41_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['target_user_id'], name='swaps_offer_target__a78160_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status'], name='swaps_offer_status_45721c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'expires_at'], name='swaps_offer_status_e674cf_idx'),
        ),
        migrations.AddIndex(
            model_name='offeritem',
            index=models.Index(fields=['offer_id'], name='swaps_offer_offer_i_f4fb11_idx'),
        ),
        migrations.AddIndex(
            model_name='offeritem',
            index=models.Index(fields=['card_id'], name='swaps_offer_card_id_b807aa_idx'),
        ),
        migrations.AddIndex(
            model_name='swapdetails',
            index=models.Index(fields=['offer_id'], name='swaps_swapd_offer_i_015893_idx'),
        ),
        migrations.AddIndex(
            model_name='swapdetails',
            index=models.Index(fields=['swap_mode'], name='swaps_swapd_swap_mo_68cc15_idx'),
        ),
    ]
