# Generated by Django 6.0.4 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0003_add_last_counteroffer_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapdetails',
            name='completed_by_initiator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swapdetails',
            name='completed_by_target',
            field=models.BooleanField(default=False),
        ),
    ]
