# Generated by Django 6.0.4 on 2026-04-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='swaps.offer'),
        ),
    ]
