# Generated by Django 6.0.4 on 2026-04-14 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scryfall_id', models.CharField(max_length=255)),
                ('card_name', models.CharField(db_index=True, max_length=255)),
                ('set_code', models.CharField(max_length=10)),
                ('set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('unused', 'Unused'), ('played', 'Played'), ('damaged', 'Damaged')], default='played', max_length=30)),
                ('is_foil', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'ordering': ['-added_at'],
            },
        ),
    ]
