# Generated by Django 6.0.4 on 2026-04-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user_id'], name='cards_card_user_id_318eab_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_name'], name='cards_card_card_na_d2b32f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user_id', 'is_available'], name='cards_card_user_id_f7b5c4_idx'),
        ),
    ]
